# Generated by Django 4.1.4 on 2022-12-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PosCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='PosProducts',
            new_name='Products',
        ),
        migrations.RenameModel(
            old_name='PosSales',
            new_name='Sales',
        ),
    ]
