# Generated by Django 4.1.4 on 2022-12-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0002_rename_poscategory_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PossalesItems',
            new_name='salesItems',
        ),
    ]
