# Generated by Django 4.1.4 on 2022-12-13 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 17, 54, 54, 86943))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catagory',
                'verbose_name_plural': 'Catagory',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 17, 54, 54, 86943))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('moto', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=16, null=True)),
                ('bin', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(upload_to=settings.models.get_upload_directory)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('invoice_print_type', models.CharField(choices=[('A4 Size', 'A4 Size'), ('1/2 of A4 Size', '1/2 of A4 Size'), ('POS', 'POS')], default='POS', max_length=15)),
            ],
            options={
                'verbose_name': 'Company Info',
                'verbose_name_plural': 'Company Info',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 17, 54, 54, 86943))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('customer_code', models.CharField(default='[C8C,C C2C,C C6C,C C7C,C C7C,C C3C]', max_length=10, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('previous_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 17, 54, 54, 86943))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('supplier_code', models.CharField(default='[S3S,S S1S,S S9S,S S9S,S S8S,S S8S]', max_length=10, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('previous_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 17, 54, 54, 86943))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'User Info',
                'verbose_name_plural': 'User Info',
            },
        ),
        migrations.CreateModel(
            name='SubCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 17, 54, 54, 86943))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_catagory', to='settings.catagory')),
            ],
            options={
                'verbose_name': 'Sub Catagory',
                'verbose_name_plural': 'Sub Catagory',
            },
        ),
    ]
