# Generated by Django 4.1.4 on 2022-12-19 06:39

import datetime
from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sales_created_at_alter_salescart_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='returened',
            new_name='returned',
        ),
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 19, 12, 39, 2, 425104), null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 39, 2, 360126)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='invoice_no',
            field=models.CharField(default=sales.models.get_invoice_number, max_length=15),
        ),
        migrations.AlterField(
            model_name='salescart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 39, 2, 360126)),
        ),
        migrations.AlterField(
            model_name='salescartamount',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 39, 2, 360126)),
        ),
    ]
