# Generated by Django 4.1.4 on 2022-12-21 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_catagory_created_at_and_more'),
        ('sales', '0008_remove_salescart_sales_rate_alter_sales_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 16, 24, 25, 198994)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 21, 16, 24, 25, 246396), null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='salescart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 16, 24, 25, 198994)),
        ),
        migrations.AlterField(
            model_name='salescart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.customer'),
        ),
        migrations.AlterField(
            model_name='salescartamount',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 16, 24, 25, 198994)),
        ),
    ]
