# Generated by Django 4.1.4 on 2022-12-30 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_created_at_alter_product_product_code_and_more'),
        ('sales', '0015_salescart_active_salescart_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 2, 12, 46, 91824)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 31, 2, 12, 46, 121868), null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='salescart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 2, 12, 46, 91824)),
        ),
        migrations.RemoveField(
            model_name='salescart',
            name='product',
        ),
        migrations.AlterField(
            model_name='salescartamount',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 2, 12, 46, 91824)),
        ),
        migrations.AddField(
            model_name='salescart',
            name='product',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
