# Generated by Django 4.1.4 on 2022-12-30 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_sales_created_at_alter_sales_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 2, 58, 55, 300063)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 31, 2, 58, 55, 322049), null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='salescart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 2, 58, 55, 300063)),
        ),
        migrations.AlterField(
            model_name='salescartamount',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 2, 58, 55, 300063)),
        ),
    ]
