# Generated by Django 4.1.4 on 2022-12-14 06:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 53, 50, 411671))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Expens Catagory',
                'verbose_name_plural': 'Expense Category',
            },
        ),
        migrations.CreateModel(
            name='ExpensesSubCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 53, 50, 411671))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensescatagory')),
            ],
            options={
                'verbose_name': 'Expense Sub Catagory',
                'verbose_name_plural': 'Expense Sub Category',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 53, 50, 411671))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 53, 50, 443652), null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensescatagory')),
                ('sub_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensessubcatagory')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expense',
            },
        ),
    ]
