# Generated by Django 4.1.4 on 2022-12-14 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0002_delete_userinfo_alter_catagory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 56, 52, 637162))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to=product.models.get_upload_directory)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Image',
            },
        ),
        migrations.CreateModel(
            name='ProductUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 56, 52, 637162))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Unit Type',
                'verbose_name_plural': 'Product Unit Type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 56, 52, 637162))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('product_code', models.CharField(default='[P7P,P P9P,P P6P,P P1P,P P6P,P P4P]', max_length=10, unique=True)),
                ('alert_qty', models.PositiveIntegerField()),
                ('purchase_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('sales_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('status', models.BooleanField(default=True)),
                ('returened', models.BooleanField(default=False)),
                ('damaged', models.BooleanField(default=False)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='settings.catagory')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productimages')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allproduct', to='product.productunittype')),
                ('sub_catagory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='settings.subcatagory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
    ]
