# Generated by Django 4.1.4 on 2022-12-14 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_created_at_alter_product_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 17, 47, 54, 498259)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='P2512618', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 17, 47, 54, 498259)),
        ),
        migrations.AlterField(
            model_name='productunittype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 17, 47, 54, 498259)),
        ),
    ]
