# Generated by Django 4.1.4 on 2022-12-30 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_in_stock_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 20, 56, 52, 513161)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='P4912596', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 20, 56, 52, 513161)),
        ),
        migrations.AlterField(
            model_name='productunittype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 20, 56, 52, 513161)),
        ),
    ]
