# Generated by Django 4.1.4 on 2022-12-19 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_alter_income_created_at_alter_income_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 39, 2, 360126)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 39, 2, 435099), null=True),
        ),
        migrations.AlterField(
            model_name='incomecatagory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 39, 2, 360126)),
        ),
        migrations.AlterField(
            model_name='incomesubcatagory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 39, 2, 360126)),
        ),
    ]
