# Generated by Django 4.1.4 on 2022-12-14 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import hrm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 56, 52, 637162))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 56, 52, 637162))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designation',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 56, 52, 637162))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(default=hrm.models.get_employee_id, max_length=12)),
                ('fullname', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('join_date', models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 56, 52, 681007))),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('health', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transport', models.DecimalField(decimal_places=2, max_digits=5)),
                ('providend_fund', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('not interested', 'not interested')], max_length=20)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('nid_number', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(max_length=150)),
                ('father_nid_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_name', models.CharField(max_length=150)),
                ('mother_nid_number', models.CharField(blank=True, max_length=20, null=True)),
                ('present_address', models.CharField(max_length=200)),
                ('permanent_address', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to=hrm.models.get_upload_directory)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.designation')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 56, 52, 637162))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('health', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transport', models.DecimalField(decimal_places=2, max_digits=5)),
                ('providend_fund', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 14, 12, 56, 52, 682002), null=True)),
                ('salary_month_unique_for_year', models.DateField(default=datetime.datetime(2022, 12, 14, 12, 56, 52, 682002), unique=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('deduction', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
            ],
            options={
                'verbose_name': 'Employee Salary Payment',
                'verbose_name_plural': 'Employee Salary Payment',
            },
        ),
    ]
