# Generated by Django 4.1.4 on 2022-12-14 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 53, 50, 411671))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Asset',
            },
        ),
    ]
