# Generated by Django 4.1.4 on 2022-12-26 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_alter_asset_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 26, 11, 6, 2, 415922), null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 11, 6, 2, 368440)),
        ),
    ]
