# Generated by Django 4.1.4 on 2022-12-14 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damages', '0002_alter_damages_created_at_alter_damages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 17, 47, 54, 498259)),
        ),
        migrations.AlterField(
            model_name='damages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 17, 47, 54, 532241), null=True),
        ),
    ]
