# Generated by Django 4.1.4 on 2022-12-21 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damages', '0009_alter_damages_created_at_alter_damages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 17, 3, 22, 781344)),
        ),
        migrations.AlterField(
            model_name='damages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 17, 3, 22, 833315), null=True),
        ),
    ]
