# Generated by Django 4.1.4 on 2022-12-30 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damages', '0019_alter_damages_created_at_alter_damages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 3, 11, 29, 480857)),
        ),
        migrations.AlterField(
            model_name='damages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 3, 11, 29, 522814), null=True),
        ),
    ]
