# Generated by Django 4.1.4 on 2022-12-29 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0012_alter_quotation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 0, 16, 43, 772983)),
        ),
        migrations.AlterField(
            model_name='quotationcart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 0, 16, 43, 772983)),
        ),
        migrations.AlterField(
            model_name='quotationcartamount',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 0, 16, 43, 772983)),
        ),
    ]
