# Generated by Django 4.1.4 on 2022-12-30 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0014_alter_quotation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 20, 56, 52, 513161)),
        ),
        migrations.AlterField(
            model_name='quotationcart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 20, 56, 52, 513161)),
        ),
        migrations.AlterField(
            model_name='quotationcartamount',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 20, 56, 52, 513161)),
        ),
    ]
