# Generated by Django 4.1.4 on 2022-12-13 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 17, 54, 54, 86943))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=150)),
                ('initial_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='BankTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 17, 54, 54, 86943))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Bank Transaction Type',
                'verbose_name_plural': 'Bank Transaction Type',
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 17, 54, 54, 86943))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('bank_transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.banktransactiontype')),
            ],
            options={
                'verbose_name': 'Bank Transactions',
                'verbose_name_plural': 'Bank Transaction',
            },
        ),
    ]
