# Generated by Django 4.1.4 on 2022-12-14 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 53, 50, 411671)),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 53, 50, 411671)),
        ),
        migrations.AlterField(
            model_name='banktransactiontype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 53, 50, 411671)),
        ),
    ]
